apiVersion: v1
kind: Service
metadata:
  name: unit-converter-service
  labels:
    app: unit-converter
spec:
  type: NodePort
  selector:
    app: unit-converter
  ports:
    - name: http
      port: 8000 # Port du Service
      targetPort: 8000 # Port du container
      nodePort: 30080 # Port externe (accessible depuis l'ext√©rieur)
      protocol: TCP

  # Session affinity (optionnel)
  sessionAffinity: None
